spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/game-db
    #url: jdbc:postgresql://game-db:5432/game-db
    username: game
    password: game
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 #Настройки пула соединений (HikariCP — дефолтный пул в Spring Boot).
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true #Показывать SQL-запросы в логах
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
feign:
  client:
    config:
      auth-service:
        connectTimeout: 5000
        readTimeout: 5000

security:
  jwt:
    secret: ${JWT_SECRET:defaultSecretKey}
    expiration: 86400000 # 24 hours
